
SELECT ?s ?s_str (GROUP_CONCAT(?spo_str; separator="\\n") AS ?text) {
SELECT
?s
?s_str
(CONCAT("<", ?s_str, ">", " ", "<", ?p_str, ">", " ", GROUP_CONCAT(?o_str; separator=', '), " .") AS ?spo_str)
    WHERE {
        ?s ?p ?o .
        FILTER(?p NOT IN (rdfs:label))
        OPTIONAL {?s rdfs:label ?s_label}
        OPTIONAL {?p rdfs:label ?p_label}
        OPTIONAL {?o rdfs:label ?o_label}
        BIND(COALESCE(?s_label, STR(?s)) AS ?s_str)
        BIND(IF(?p = rdf:type,
                "is a",
                IF( ?p = rdfs:comment,
                    " ",
                    COALESCE(?p_label, STR(?p))
                )
              )
              AS ?p_str)
        BIND(IF(isLiteral(?o), STR(?o), COALESCE(?o_label, STR(?o))) AS ?o_str)

        BIND(CONCAT("<", ?p_str, "> <", ?o_str, "> ") AS ?po_str)

    } GROUP BY ?s ?s_str ?p

} GROUP BY ?s ?s_str
